# Generated by Django 5.0.9 on 2026-03-14 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shoporder'),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='new', max_length=15, verbose_name='Статус')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='orders.order', verbose_name='Заказ')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to='shops.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Статус заказа у поставщика',
                'verbose_name_plural': 'Статусы заказов у поставщиков',
                'unique_together': {('order', 'shop')},
            },
        ),
    ]
