# Generated by Django 5.0.9 on 2026-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('basket', 'Корзина'), ('new', 'Новый'), ('confirmed', 'Подтверждён'), ('assembled', 'Собран'), ('sent', 'Отправлен'), ('partially_sent', 'Отправлен частично'), ('delivered', 'Доставлен'), ('cancelled', 'Отменён')], default='basket', max_length=15, verbose_name='Статус'),
        ),
    ]
