# Generated by Django 5.0.9 on 2026-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='external_id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Внешний ID'),
        ),
    ]
